elementweb:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.dabvastur-lab.site"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hosts:
      - host: &frontend_host chat.dabvastur-lab.site
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: element-tls-certificate
        hosts:
          - *frontend_host
  config:
    default:
      base_url: https://matrix.dabvastur-lab.site
      server_name: dabvastur-lab.site

dendrite:
  dendrite_config:
    global:
      server_name: matrix.dabvastur-lab.site
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostName: matrix.dabvastur-lab.site
    tls:
      - hosts:
          - matrix.dabvastur-lab.site
        secretName: matrix-tls-certificate
  postgresql:
    enabled: true
